/**
 * Report Templates for PDF Export
 *
 * Pre-built templates for different report types:
 * - Code Review Report
 * - Test Generation Report
 * - Project Analysis Report
 * - Documentation Report
 *
 * @module report-templates
 */

import type {
  PDFExportOptions,
  CodeReviewReportData,
  TestGenerationReportData,
  ProjectAnalysisReportData,
} from '../pdf-export'

// ============================================================================
// Template Registry
// ============================================================================

export type TemplateType = 'code-review' | 'test-report' | 'project-analysis' | 'doc-generation'

export interface TemplateConfig {
  type: TemplateType
  name: string
  description: string
  generateHTML: (data: unknown) => string
  getDefaultOptions: () => Partial<PDFExportOptions>
}

// ============================================================================
// Code Review Template
// ============================================================================

export const codeReviewTemplate: TemplateConfig = {
  type: 'code-review',
  name: 'Code Review Report',
  description: 'Professional code review report with issue categorization',
  generateHTML: (data: unknown) => {
    const reviewData = data as CodeReviewReportData
    return generateCodeReviewTemplate(reviewData)
  },
  getDefaultOptions: () => ({
    title: 'Code Review Report',
    includeTOC: false,
    pageNumbers: true,
    header: 'Code Review',
    footer: 'Generated by AI Workspace',
  }),
}

/**
 * Generate code review report HTML
 */
export function generateCodeReviewTemplate(data: CodeReviewReportData): string {
  const errorCount = data.issues.filter((i) => i.severity === 'error').length
  const warningCount = data.issues.filter((i) => i.severity === 'warning').length
  const infoCount = data.issues.filter((i) => i.severity === 'info').length

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; }
        .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e2e8f0; }
        .header h1 { font-size: 28px; color: #0f172a; margin-bottom: 8px; }
        .header .subtitle { color: #64748b; font-size: 14px; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 40px; }
        .summary-card { padding: 20px; border-radius: 12px; text-align: center; }
        .summary-card.errors { background: linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%); }
        .summary-card.warnings { background: linear-gradient(135deg, #fefce8 0%, #fef3c7 100%); }
        .summary-card.suggestions { background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%); }
        .summary-card .number { font-size: 36px; font-weight: 700; }
        .summary-card.errors .number { color: #dc2626; }
        .summary-card.warnings .number { color: #d97706; }
        .summary-card.suggestions .number { color: #16a34a; }
        .summary-card .label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
        .section { margin-bottom: 32px; }
        .section h2 { font-size: 18px; color: #334155; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }
        .issue { padding: 16px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid; }
        .issue.error { background: #fef2f2; border-color: #ef4444; }
        .issue.warning { background: #fefce8; border-color: #eab308; }
        .issue.info { background: #f0fdf4; border-color: #22c55e; }
        .issue-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px; }
        .issue-title { font-weight: 600; font-size: 14px; }
        .issue.error .issue-title { color: #991b1b; }
        .issue.warning .issue-title { color: #854d0e; }
        .issue.info .issue-title { color: #166534; }
        .issue-meta { font-size: 11px; color: #64748b; }
        .issue-location { background: #e2e8f0; padding: 2px 8px; border-radius: 4px; font-family: monospace; }
        .issue-body { font-size: 13px; color: #475569; }
        .issue-suggestion { margin-top: 12px; padding-top: 12px; border-top: 1px dashed #cbd5e1; font-size: 13px; }
        .issue-suggestion strong { color: #64748b; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; font-weight: 600; text-transform: uppercase; }
        .badge.error { background: #fee2e2; color: #dc2626; }
        .badge.warning { background: #fef3c7; color: #d97706; }
        .badge.info { background: #dcfce7; color: #16a34a; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Code Review Report</h1>
          <p class="subtitle">${escapeHtml(data.file)}</p>
          <p class="subtitle">Generated: ${new Date().toLocaleString()}</p>
        </div>

        <div class="summary">
          <div class="summary-card errors">
            <div class="number">${errorCount}</div>
            <div class="label">Errors</div>
          </div>
          <div class="summary-card warnings">
            <div class="number">${warningCount}</div>
            <div class="label">Warnings</div>
          </div>
          <div class="summary-card suggestions">
            <div class="number">${infoCount}</div>
            <div class="label">Suggestions</div>
          </div>
        </div>

        ${renderIssuesByCategory(data.issues)}
      </div>
    </body>
    </html>
  `
}

/**
 * Render issues grouped by category
 */
function renderIssuesByCategory(issues: CodeReviewReportData['issues']): string {
  const categories: Record<string, typeof issues> = {
    security: issues.filter((i: (typeof issues)[0]) => i.category === 'security'),
    performance: issues.filter((i: (typeof issues)[0]) => i.category === 'performance'),
    style: issues.filter((i: (typeof issues)[0]) => i.category === 'style'),
    'best-practice': issues.filter((i: (typeof issues)[0]) => i.category === 'best-practice'),
  }

  const categoryNames: Record<string, string> = {
    security: 'Security Issues',
    performance: 'Performance Issues',
    style: 'Style Issues',
    'best-practice': 'Best Practices',
  }

  return Object.entries(categories)
    .filter(([, items]) => items.length > 0)
    .map(
      ([category, items]) => `
      <div class="section">
        <h2>${categoryNames[category] || category} (${items.length})</h2>
        ${items
          .map(
            (issue) => `
          <div class="issue ${issue.severity}">
            <div class="issue-header">
              <span class="issue-title">${escapeHtml(issue.message)}</span>
              <span class="badge ${issue.severity}">${issue.severity}</span>
            </div>
            <div class="issue-meta">
              <span class="issue-location">Line ${issue.line}:${issue.column}</span>
              <span style="margin-left: 8px;">${issue.rule}</span>
            </div>
            ${
              issue.suggestion
                ? `
              <div class="issue-suggestion">
                <strong>Suggestion:</strong> ${escapeHtml(issue.suggestion)}
              </div>
            `
                : ''
            }
          </div>
        `
          )
          .join('')}
      </div>
    `
    )
    .join('')
}

// ============================================================================
// Test Report Template
// ============================================================================

export const testReportTemplate: TemplateConfig = {
  type: 'test-report',
  name: 'Test Generation Report',
  description: 'Test templates and coverage summary',
  generateHTML: (data: unknown) => {
    const testData = data as TestGenerationReportData
    return generateTestReportTemplate(testData)
  },
  getDefaultOptions: () => ({
    title: 'Test Report',
    includeTOC: false,
    pageNumbers: true,
    header: 'Test Generation',
    footer: 'Generated by AI Workspace',
  }),
}

/**
 * Generate test report HTML
 */
export function generateTestReportTemplate(data: TestGenerationReportData): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; }
        .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e2e8f0; }
        .header h1 { font-size: 28px; color: #0f172a; margin-bottom: 8px; }
        .header .subtitle { color: #64748b; font-size: 14px; }
        .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 40px; }
        .summary-card { padding: 16px; border-radius: 8px; text-align: center; background: #f1f5f9; }
        .summary-card .number { font-size: 28px; font-weight: 700; color: #1e40af; }
        .summary-card .label { font-size: 11px; color: #64748b; text-transform: uppercase; }
        .section { margin-bottom: 32px; }
        .section h2 { font-size: 18px; color: #334155; margin-bottom: 16px; }
        .template { padding: 12px 16px; background: #f8fafc; border-radius: 6px; margin-bottom: 8px; border-left: 3px solid #6366f1; }
        .template-name { font-weight: 600; color: #1e293b; }
        .template-type { font-size: 11px; color: #6366f1; background: #eef2ff; padding: 2px 8px; border-radius: 12px; margin-left: 8px; }
        .template-body { margin-top: 8px; font-family: 'SF Mono', Monaco, monospace; font-size: 12px; background: #1e293b; color: #e2e8f0; padding: 12px; border-radius: 4px; overflow-x: auto; white-space: pre; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Test Generation Report</h1>
          <p class="subtitle">Source: ${escapeHtml(data.file)}</p>
          <p class="subtitle">Test File: ${escapeHtml(data.testFile)}</p>
          <p class="subtitle">Framework: ${data.framework}</p>
        </div>

        <div class="summary">
          <div class="summary-card">
            <div class="number">${data.summary.functionsFound}</div>
            <div class="label">Functions</div>
          </div>
          <div class="summary-card">
            <div class="number">${data.summary.componentsFound}</div>
            <div class="label">Components</div>
          </div>
          <div class="summary-card">
            <div class="number">${data.summary.hooksFound}</div>
            <div class="label">Hooks</div>
          </div>
          <div class="summary-card">
            <div class="number">${data.summary.classesFound}</div>
            <div class="label">Classes</div>
          </div>
        </div>

        <div class="section">
          <h2>Generated Test Templates (${data.templates.length})</h2>
          ${data.templates
            .map(
              (template) => `
            <div class="template">
              <span class="template-name">${escapeHtml(template.name)}</span>
              <span class="template-type">${template.type}</span>
            </div>
          `
            )
            .join('')}
        </div>
      </div>
    </body>
    </html>
  `
}

// ============================================================================
// Project Analysis Template
// ============================================================================

export const projectAnalysisTemplate: TemplateConfig = {
  type: 'project-analysis',
  name: 'Project Analysis Report',
  description: 'Project structure and statistics summary',
  generateHTML: (data: unknown) => {
    const analysisData = data as ProjectAnalysisReportData
    return generateProjectAnalysisTemplate(analysisData)
  },
  getDefaultOptions: () => ({
    title: 'Project Analysis',
    includeTOC: true,
    pageNumbers: true,
    header: 'Project Analysis',
    footer: 'Generated by AI Workspace',
  }),
}

/**
 * Generate project analysis HTML
 */
export function generateProjectAnalysisTemplate(data: ProjectAnalysisReportData): string {
  const languages = Object.entries(data.summary.languages)
    .sort((a, b) => (b[1] as number) - (a[1] as number))
    .map(([lang, count]) => ({ lang, count: count as number }))
  const fileTypes = Object.entries(data.structure.filesByType)
    .sort((a, b) => (b[1] as number) - (a[1] as number))
    .map(([ext, count]) => ({ ext, count: count as number }))

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; }
        .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e2e8f0; }
        .header h1 { font-size: 28px; color: #0f172a; margin-bottom: 8px; }
        .header .subtitle { color: #64748b; font-size: 14px; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 40px; }
        .summary-card { padding: 20px; border-radius: 12px; text-align: center; background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); }
        .summary-card .number { font-size: 36px; font-weight: 700; color: #1e40af; }
        .summary-card .label { font-size: 12px; color: #64748b; text-transform: uppercase; }
        .section { margin-bottom: 32px; }
        .section h2 { font-size: 18px; color: #334155; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }
        .lang-grid { display: flex; flex-wrap: wrap; gap: 8px; }
        .lang-tag { background: #e2e8f0; padding: 6px 14px; border-radius: 20px; font-size: 13px; }
        .file-table { width: 100%; border-collapse: collapse; }
        .file-table th, .file-table td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        .file-table th { background: #f8fafc; font-weight: 600; color: #64748b; font-size: 12px; text-transform: uppercase; }
        .file-table td { font-size: 13px; }
        .file-path { font-family: 'SF Mono', Monaco, monospace; color: #475569; }
        .file-lines { color: #64748b; }
        .progress-bar { background: #e2e8f0; border-radius: 4px; height: 8px; overflow: hidden; }
        .progress-fill { background: #6366f1; height: 100%; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Project Analysis Report</h1>
          <p class="subtitle">${escapeHtml(data.projectName)}</p>
          <p class="subtitle">Analysis Date: ${data.analysisDate}</p>
        </div>

        <div class="summary">
          <div class="summary-card">
            <div class="number">${data.summary.totalFiles}</div>
            <div class="label">Total Files</div>
          </div>
          <div class="summary-card">
            <div class="number">${data.summary.totalLines.toLocaleString()}</div>
            <div class="label">Total Lines</div>
          </div>
          <div class="summary-card">
            <div class="number">${data.structure.directories}</div>
            <div class="label">Directories</div>
          </div>
        </div>

        <div class="section">
          <h2>Languages</h2>
          <div class="lang-grid">
            ${languages
              .map(
                (l) => `
              <span class="lang-tag">${escapeHtml(l.lang)}: ${l.count}</span>
            `
              )
              .join('')}
          </div>
        </div>

        <div class="section">
          <h2>File Types</h2>
          <table class="file-table">
            <thead>
              <tr>
                <th>Extension</th>
                <th>Count</th>
                <th>Distribution</th>
              </tr>
            </thead>
            <tbody>
              ${fileTypes
                .map(
                  (ft) => `
                <tr>
                  <td class="file-path">${escapeHtml(ft.ext)}</td>
                  <td>${ft.count}</td>
                  <td style="width: 40%;">
                    <div class="progress-bar">
                      <div class="progress-fill" style="width: ${(ft.count / data.summary.totalFiles) * 100}%"></div>
                    </div>
                  </td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>
        </div>

        <div class="section">
          <h2>Largest Files</h2>
          <table class="file-table">
            <thead>
              <tr>
                <th>File</th>
                <th>Lines</th>
              </tr>
            </thead>
            <tbody>
              ${data.summary.largestFiles
                .slice(0, 10)
                .map(
                  (f: { path: string; lines: number }) => `
                <tr>
                  <td class="file-path">${escapeHtml(f.path)}</td>
                  <td class="file-lines">${f.lines.toLocaleString()}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>
        </div>
      </div>
    </body>
    </html>
  `
}

// ============================================================================
// Template Registry
// ============================================================================

export const templates: Record<TemplateType, TemplateConfig> = {
  'code-review': codeReviewTemplate,
  'test-report': testReportTemplate,
  'project-analysis': projectAnalysisTemplate,
  'doc-generation': {
    type: 'doc-generation',
    name: 'Documentation Report',
    description: 'Generated documentation summary',
    generateHTML: () => '<div>Documentation template</div>',
    getDefaultOptions: () => ({
      title: 'Documentation',
      includeTOC: true,
      pageNumbers: true,
      header: 'Documentation',
      footer: 'Generated by AI Workspace',
    }),
  },
}

/**
 * Get template by type
 */
export function getTemplate(type: TemplateType): TemplateConfig | undefined {
  return templates[type]
}

/**
 * Get all available templates
 */
export function getAllTemplates(): TemplateConfig[] {
  return Object.values(templates)
}

/**
 * Apply template to data
 */
export function applyTemplate<T>(type: TemplateType, data: T): string {
  const template = getTemplate(type)
  if (!template) {
    throw new Error(`Unknown template type: ${type}`)
  }
  return template.generateHTML(data)
}

// ============================================================================
// Utility
// ============================================================================

function escapeHtml(text: string): string {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}
