import type { Metadata, Viewport } from 'next'
import './globals.css'
import 'sonner/dist/styles.css'

/**
 * Deployment-region locale switch — build-time inlined.
 *
 * The domestic (weave.eo2suite.cn) and international (weave.eo2suite.com)
 * sites are BUILT separately: the CN build sets NEXT_PUBLIC_DEPLOY_REGION=cn,
 * the international build sets it to `global`. next.config.mjs FAILS the
 * production build when the variable is missing or invalid, so every
 * deployment is guaranteed to carry an explicit region. Dev defaults to
 * English. Mirrors the pattern in app/help/privacy/page.tsx.
 */
const IS_CN_BUILD = process.env.NEXT_PUBLIC_DEPLOY_REGION === 'cn'

const metadataByRegion: Metadata = IS_CN_BUILD
  ? {
      title: '怡氧知知',
      description: '面向创作者的 AI 原生工作台：本地优先的文件、知识工作流与多智能体编排',
    }
  : {
      title: 'EO2Weave',
      description: 'AI-native creator workspace with local-first files, knowledge workflows, and multi-agent orchestration',
    }

export const metadata: Metadata = {
  ...metadataByRegion,
  // manifest.webmanifest is generated by app/manifest.ts (force-static).
  // Icons come from browser-extension/public via scripts/prepare-pwa.mjs.
  // Declaring them here stops browsers from auto-requesting /favicon.ico,
  // which does not exist (it previously fell into the legacy [...path]
  // catch-all and returned a server error).
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' },
    ],
    apple: [{ url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' }],
  },
}

// Viewport settings — restores the pre-Next PWA behaviour from the old
// Vite index.html: viewport-fit=cover is required for env(safe-area-inset-*)
// on notched devices (PWA standalone mode), and zoom is disabled to match
// the app-like input experience (double-tap zoom fights the editor UI).
// themeColor uses the brand primary baseline (--primary-500 = #4D9F98 in
// globals.css); the OS UI chrome (address bar / status bar) follows it.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  themeColor: '#4D9F98',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang={IS_CN_BUILD ? 'zh-CN' : 'en'}>
      <body>{children}</body>
    </html>
  )
}
