import type { Metadata } from 'next'
import './globals.css'
import 'sonner/dist/styles.css'

export const metadata: Metadata = {
  title: 'EO2Weave',
  description: 'AI-native creator workspace with local-first files, knowledge workflows, and multi-agent orchestration',
  // manifest.webmanifest is generated by app/manifest.ts (force-static).
  // Icons come from browser-extension/public via scripts/prepare-pwa.mjs.
  // Declaring them here stops browsers from auto-requesting /favicon.ico,
  // which does not exist (it previously fell into the legacy [...path]
  // catch-all and returned a server error).
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' },
    ],
    apple: [{ url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' }],
  },
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  )
}
