import type { Metadata, Viewport } from 'next'
import './globals.css'
import 'sonner/dist/styles.css'

export const metadata: Metadata = {
  title: 'EO2Weave',
  description: 'AI-native creator workspace with local-first files, knowledge workflows, and multi-agent orchestration',
  // manifest.webmanifest is generated by app/manifest.ts (force-static).
  // Icons come from browser-extension/public via scripts/prepare-pwa.mjs.
  // Declaring them here stops browsers from auto-requesting /favicon.ico,
  // which does not exist (it previously fell into the legacy [...path]
  // catch-all and returned a server error).
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' },
    ],
    apple: [{ url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' }],
  },
}

// Viewport settings — restores the pre-Next PWA behaviour from the old
// Vite index.html: viewport-fit=cover is required for env(safe-area-inset-*)
// on notched devices (PWA standalone mode), and zoom is disabled to match the
// app-like input experience (double-tap zoom fights the editor UI).
// themeColor uses the brand primary baseline (--primary-500 = #4D9F98 in
// globals.css); the OS UI chrome (address bar / status bar) follows it.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  themeColor: '#4D9F98',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  )
}
