import { defineConfig } from 'wxt';

export default defineConfig({
  outDir: 'dist',
  manifest: {
    name: 'CreatorWeave',
    description: 'Provides web_search and web_fetch capabilities for in-browser Agents',
    version: '1.0.1',
    permissions: ['scripting', 'tabs'],
    host_permissions: ['<all_urls>'],
    // icons and action icon are auto-generated by WXT from public/icon.png
  },
});
