import { defineConfig } from 'wxt';
import pkg from './package.json';

// Stable Chromium extension key (RSA public key DER, base64).
// Keeps a consistent extension ID across loads/updates so the native messaging
// manifest's `allowed_origins` stays valid. Override at build time via
// CREATORWEAVE_CHROMIUM_EXTENSION_KEY if you need a different key pair.
const DEFAULT_CHROMIUM_EXTENSION_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq7brlUY/QJP5fnbKrcvOAbirr3GLFgiXDbT2g8D5NKi8GDVBp+OIHCt96LsJ3zTiFlvx4W7bhcvX5JF3eUfP0qjLaaoUw8b683Uupui3iLPaGYrVDxFRNYJR28BDUtExCkb/rehk/QVtLapPVB63YboFzuU2L0SUyGjfzXi6sLYOIFGnYfrrcLQu3pLf+iuRr04yjkfcvlXIG3Ws+Am5AfFFvWxYX1zvV58GyHM5kaKZy2MqugOMiwbQvID5Lkm35NhOxpO/lrjrOy5ZhNObiWZZk70VzJxGM3saE/q/aUEeOwY+0RLqzWb7cs/f8E1tMxB23rifheL7M58tuFpXDwIDAQAB';

export default defineConfig({
  outDir: 'dist',
  // Dev mode outputs to `dist/chrome-mv3` (not the default `chrome-mv3-dev`),
  // so the web app's vite-plugin-extension-serve (which watches dist/chrome-mv3)
  // serves the DEV build. Without this, dev artifacts land in chrome-mv3-dev and
  // the web keeps serving the stale PROD build → popup shows PROD.
  outDirTemplate: '{{browser}}-mv{{manifestVersion}}',
  // Don't auto-launch a separate browser during `wxt dev`. CreatorWeave loads
  // the extension via a zip downloaded from the web app, not via web-ext's
  // managed browser. The manual runner just logs the output path.
  runner: {
    disabled: true,
  },
  manifest: {
    name: '__MSG_extensionName__',
    description: '__MSG_extensionDescription__',
    default_locale: 'en',
    version: pkg.version,
    // Pin a stable extension ID derived from a fixed public key.
    key: process.env.CREATORWEAVE_CHROMIUM_EXTENSION_KEY || DEFAULT_CHROMIUM_EXTENSION_KEY,
    permissions: ['scripting', 'tabs', 'storage', 'alarms', 'notifications', 'sidePanel', 'nativeMessaging'],
    host_permissions: ['<all_urls>'],
    // Fixed Firefox add-on ID for native messaging registration.
    browser_specific_settings: {
      gecko: {
        id: 'creatorweave-bridge@creatorweave.local',
      },
    },
    // No global side_panel config — side panel is only enabled per-tab
    // via setOptions({ tabId }) when user clicks the workspace assistant button.
    // icons and action icon are auto-generated by WXT from public/icon.png
  },
});
