import { defineConfig } from 'wxt';
import pkg from './package.json';

export default defineConfig({
  outDir: 'dist',
  manifest: {
    name: 'CreatorWeave',
    description: 'Provides web_search and web_fetch capabilities for in-browser Agents',
    version: pkg.version,
    permissions: ['scripting', 'tabs', 'storage', 'alarms', 'notifications', 'sidePanel'],
    host_permissions: ['<all_urls>'],
    // No global side_panel config — side panel is only enabled per-tab
    // via setOptions({ tabId }) when user clicks the workspace assistant button.
    // icons and action icon are auto-generated by WXT from public/icon.png
  },
});
