#!/usr/bin/env node
// One-off rebrand script: CreatorWeave -> EO2Weave / eo2weave / 怡氧知知
// Run from repo root: node scripts/rebrand-web.mjs
import fs from 'node:fs'

const rep = (p, pairs) => {
  let s = fs.readFileSync(p, 'utf8')
  for (const [a, b] of pairs) {
    if (!s.includes(a)) console.warn(`  !! NOT FOUND in ${p}: ${JSON.stringify(a.slice(0, 60))}`)
    s = s.split(a).join(b)
  }
  fs.writeFileSync(p, s)
  console.log(`${p} ok, CreatorWeave left: ${(s.match(/CreatorWeave/g) || []).length}`)
}

// ── 簇1 入口/PWA ──
rep('web/public/manifest.json', [
  ['"name": "CreatorWeave"', '"name": "EO2Weave"'],
  ['"short_name": "CWeave"', '"short_name": "EO2Weave"'],
])
rep('web/public/manifest.webmanifest.json', [
  ['"name": "CreatorWeave"', '"name": "EO2Weave"'],
  ['"short_name": "CWeave"', '"short_name": "EO2Weave"'],
])
rep('web/sw.ts', [
  ["title: 'CreatorWeave',", "title: 'EO2Weave',"],
])
rep('mobile-web/index.html', [
  ['content="CreatorWeave 移动端 - 远程控制你的 AI 创作工作台"',
   'content="怡氧知知（EO2Weave）移动端 - 远程控制你的 AI 创作工作台"'],
  ['<title>CreatorWeave</title>', '<title>EO2Weave</title>'],
])
rep('mobile-web/src/pages/SettingsPage.tsx', [
  ['CreatorWeave Remote v1.0.0', 'EO2Weave Remote v1.0.0'],
])

// ── 簇3 AI 提示词/错误文案 ──
rep('web/agent/prompts/universal-system-prompt.ts', [
  ['CreatorWeave can render', 'EO2Weave can render'],
  ['or CreatorWeave APIs', 'or eo2weave APIs'],
  ['CreatorWeave renders', 'EO2Weave renders'],
])
rep('web/agent/workspace-assistant-context.ts', [
  ["hint: 'Is the CreatorWeave browser extension installed and active on this origin?'",
   "hint: 'Is the eo2weave browser extension installed and active on this origin?'"],
  ['[Source — read live by CreatorWeave]', '[Source — read live by eo2weave]'],
  ['a CreatorWeave recipe', 'an eo2weave recipe'],
])
rep('web/agent/tools/page-action-bridge.ts', [
  ['Page action requires the CreatorWeave Browser Extension. Install/enable it and reopen the side panel.',
   'Page action requires the eo2weave browser extension. Install/enable it and reopen the side panel.'],
  ['(when CreatorWeave is docked to an upstream tab)', '(when eo2weave is docked to an upstream tab)'],
  ['Screenshot requires the CreatorWeave Browser Extension.', 'Screenshot requires the eo2weave browser extension.'],
])
rep('web/agent/tools/page-read.tool.ts', [
  ['Open CreatorWeave as a side panel', 'Open eo2weave as a side panel'],
])

// ── 簇4 导出产物品牌 ──
rep('web/export/templates/report-templates.ts', [
  ["'Generated by CreatorWeave'", "'Generated by eo2weave'"],
])
rep('web/export/pdf-export.ts', [
  ["author = 'CreatorWeave',", "author = 'EO2Weave',"],
  ["'Generated by CreatorWeave'", "'Generated by eo2weave'"],
])
rep('web/storage/diagnostics.ts', [
  ['# CreatorWeave 诊断报告', '# 怡氧知知诊断报告'],
])
rep('web/storage/__tests__/diagnostics.test.ts', [
  ["'# CreatorWeave 诊断报告'", "'# 怡氧知知诊断报告'"],
])
rep('web/store/conversation.store.sqlite.ts', [
  ["'CreatorWeave Agent'", "'EO2Weave Agent'"],
])
rep('web/opfs/backup.ts', [
  ['creatorweave-backup_', 'eo2weave-backup_'],
])

// ── 簇5 MCP/设置引导 ──
rep('web/mcp/preset-providers.ts', [
  ['3. Paste your token into the Auth Token field in CreatorWeave',
   '3. Paste your token into the Auth Token field in eo2weave'],
  ["'CreatorWeave Mail MCP server", "'EO2Weave Mail MCP server"],
  ['4. Paste the same Personal Mail Token into CreatorWeave:',
   '4. Paste the same Personal Mail Token into eo2weave:'],
])
rep('web/components/mcp/MCPSettings.tsx', [
  ['require the CreatorWeave browser extension', 'require the eo2weave browser extension'],
])
rep('web/components/settings/SettingsDialog.tsx', [
  ['`CreatorWeave v${version}', '`EO2Weave v${version}'],
])

console.log('\nAll done.')
