/**
 * Plugin Worker - String-based API (v2.0.0)
 *
 * This worker runs in a separate thread to prevent blocking the main thread.
 * Uses wasm-bindgen String types for automatic memory conversion.
 *
 * Required plugin exports:
 * - get_plugin_info() -> String
 * - process_file(input_json: String) -> String
 * - finalize(outputs_json: String) -> String
 * - cleanup()
 */

//=============================================================================
// Type Definitions
//=============================================================================

interface PluginMetadata {
  id: string
  name: string
  version: string
  api_version: string
  description: string
  author: string
  capabilities: {
    metadata_only: boolean
    requires_content: boolean
    supports_streaming: boolean
    max_file_size: number
    file_extensions: string[]
  }
  resource_limits?: {
    max_memory: number
    max_execution_time: number
    worker_count: number
  }
}

interface FileInput {
  path: string
  name: string
  size?: number
  content?: Uint8Array
  mime_type?: string
  last_modified?: number
  is_directory?: boolean
}

interface PluginOutput {
  status: string
  data?: unknown
  error?: string
}

interface StreamChunk {
  index: number
  data: string
  offset: number
  isLast: boolean
}

export type WorkerMessage =
  | { type: 'LOAD'; payload: { pluginId: string } }
  | { type: 'EXECUTE'; payload: { fileInput: FileInput } }
  | { type: 'FINALIZE'; payload: { outputs: PluginOutput[] } }
  | { type: 'CLEANUP' }
  | { type: 'STREAM_START'; payload: { file: File; chunkSize: number } }
  | { type: 'STREAM_CHUNK'; payload: { chunk: StreamChunk; index: number } }
  | { type: 'STREAM_END' }
  | { type: 'STREAM_ERROR'; payload: { error: string } }
  // Tool ABI messages
  | { type: 'GET_TOOL_SCHEMA' }
  | { type: 'EXECUTE_TOOL'; payload: { input: string } }

interface WasmExports {
  get_plugin_info: () => string
  process_file: (input: string) => string
  finalize?: (outputs: string) => string
  cleanup?: () => void
  // Tool ABI (optional)
  get_tool_schema?: () => string
  execute_tool?: (input: string) => string
}

// Worker state
let wasmExports: WasmExports | null = null
let pluginMetadata: PluginMetadata | null = null

//=============================================================================
// Message Handler
//=============================================================================

console.log('[PluginWorker] Worker initialized')

self.onmessage = async (event: MessageEvent) => {
  const message = event.data
  console.log('[PluginWorker] Received message:', message.type, message.payload)

  try {
    switch (message.type) {
      case 'LOAD':
        await handleLoad(message.payload)
        break

      case 'EXECUTE':
        await handleExecute(message.payload)
        break

      case 'FINALIZE':
        await handleFinalize(message.payload)
        break

      case 'CLEANUP':
        handleCleanup()
        break

      case 'STREAM_START':
        await handleStreamStart(message.payload)
        break

      case 'STREAM_CHUNK':
        await handleStreamChunk(message.payload)
        break

      case 'STREAM_END':
        handleStreamEnd()
        break

      case 'STREAM_ERROR':
        handleStreamError(message.payload)
        break

      case 'GET_TOOL_SCHEMA':
        handleGetToolSchema()
        break

      case 'EXECUTE_TOOL':
        handleExecuteTool(message.payload)
        break

      default:
        sendError(`Unknown message type: ${(message as any).type}`)
    }
  } catch (error) {
    sendError(`Worker error: ${error}`)
  }
}

//=============================================================================
// Load Plugin
//=============================================================================

async function handleLoad(payload: { pluginId: string }) {
  const { pluginId } = payload
  console.log('[PluginWorker] Loading plugin:', pluginId)

  try {
    // Convert plugin ID from dashes to underscores for WASM file naming
    const wasmId = pluginId.replace(/-/g, '_')

    // Load the JS module generated by wasm-pack
    // In Vite, files in /public/wasm are served at /wasm/
    const jsModulePath = `/wasm/${wasmId}.js`
    console.log('[PluginWorker] Loading JS module:', jsModulePath)

    // Use dynamic import with full URL
    const moduleUrl = new URL(jsModulePath, self.location.href).href
    const module = await import(/* @vite-ignore */ moduleUrl)
    console.log(
      '[PluginWorker] JS module loaded, module exports:',
      Object.keys(module).filter((k) => !k.startsWith('__'))
    )

    // Initialize the WASM module
    // The new wasm-bindgen API expects an object with module_or_path property
    const wasmUrl = `/wasm/${wasmId}_bg.wasm`
    console.log('[PluginWorker] Initializing WASM from:', wasmUrl)

    // The default export initializes the WASM module
    await module.default({ module_or_path: wasmUrl })
    console.log('[PluginWorker] WASM module initialized')

    // The named exports are the JS wrapper functions we need to use
    // NOT the raw WASM exports returned by the init function
    wasmExports = module as WasmExports
    console.log(
      '[PluginWorker] Available wrapper exports:',
      Object.keys(wasmExports).filter((k) => !k.startsWith('__'))
    )

    // Get plugin metadata using String API v2.0.0
    if (wasmExports && typeof wasmExports.get_plugin_info !== 'function') {
      throw new Error(
        `Plugin must export get_plugin_info() -> String function. Available exports: ${Object.keys(
          wasmExports
        )
          .filter((k) => !k.startsWith('__'))
          .join(', ')}`
      )
    }

    console.log('[PluginWorker] Calling get_plugin_info()...')
    const metadataValue = wasmExports?.get_plugin_info()
    console.log('[PluginWorker] get_plugin_info() returned:', metadataValue, typeof metadataValue)
    if (metadataValue === undefined) {
      // Try to check if there's a different export name
      console.log('[PluginWorker] Checking all exports:', Object.keys(wasmExports ?? {}))
      throw new Error(
        'get_plugin_info() returned undefined. Plugin may not be properly initialized.'
      )
    }
    pluginMetadata = JSON.parse(metadataValue ?? '{}')
    console.log('[PluginWorker] Plugin metadata:', pluginMetadata)

    // Validate API version
    if (pluginMetadata && pluginMetadata.api_version && pluginMetadata.api_version !== '2.0.0') {
      throw new Error(
        `Plugin API version ${pluginMetadata.api_version} is not supported. Expected 2.0.0`
      )
    }

    sendResponse({
      type: 'LOADED',
      payload: {
        metadata: pluginMetadata,
        pluginId,
      },
    })
  } catch (e) {
    console.error('[PluginWorker] Failed to load plugin:', e)
    sendError(`Failed to load plugin: ${e}`)
  }
}

//=============================================================================
// Execute Plugin on File
//=============================================================================

async function handleExecute(payload: { fileInput: FileInput }) {
  const { fileInput } = payload
  console.log('[PluginWorker] Executing plugin for file:', fileInput.path)

  try {
    if (!wasmExports) {
      throw new Error('Plugin not loaded')
    }

    if (typeof wasmExports.process_file !== 'function') {
      throw new Error(`Plugin must export process_file(input_json: String) -> String function`)
    }

    // Convert Uint8Array to regular array for proper JSON serialization
    const inputForJson = {
      ...fileInput,
      content: fileInput.content ? Array.from(fileInput.content) : undefined,
    }

    // Serialize to JSON
    const inputJson = JSON.stringify(inputForJson)
    console.log('[PluginWorker] Input JSON size:', inputJson.length, 'bytes')

    // Call process_file - takes String, returns String (wasm-bindgen handles memory)
    const outputJson = wasmExports.process_file(inputJson)
    console.log('[PluginWorker] Output JSON (first 200 chars):', outputJson.substring(0, 200))

    // Parse result
    let output
    try {
      output = JSON.parse(outputJson)
    } catch (e) {
      console.error('[PluginWorker] Failed to parse output JSON:', e)
      throw new Error(`Invalid output JSON: ${e}`)
    }

    console.log('[PluginWorker] Parsed output status:', output.status)

    sendResponse({
      type: 'RESULT',
      payload: {
        output,
        fileId: fileInput.path,
      },
    })
  } catch (error) {
    console.error('[PluginWorker] Execution error:', error)
    sendError(`Execution failed: ${error}`)
  }
}

//=============================================================================
// Finalize Plugin Results
//=============================================================================

async function handleFinalize(payload: { outputs: PluginOutput[] }) {
  const { outputs } = payload

  try {
    if (!wasmExports) {
      throw new Error('Plugin not loaded')
    }

    if (typeof wasmExports.finalize !== 'function') {
      throw new Error(`Plugin must export finalize(outputs_json: String) -> String function`)
    }

    // Serialize outputs array
    const outputsJson = JSON.stringify(outputs)
    console.log(
      '[PluginWorker] Finalize outputs JSON (first 500 chars):',
      outputsJson.substring(0, 500)
    )

    // Call finalize - takes String, returns String
    const resultJson = wasmExports.finalize(outputsJson)
    console.log('[PluginWorker] Finalize result (first 200 chars):', resultJson.substring(0, 200))

    let result
    try {
      result = JSON.parse(resultJson)
    } catch (e) {
      console.error('[PluginWorker] Failed to parse result JSON:', e)
      throw new Error(`Invalid result JSON: ${e}`)
    }

    sendResponse({
      type: 'RESULT',
      payload: {
        result,
        pluginId: pluginMetadata?.id,
      },
    })
  } catch (error) {
    console.error('[PluginWorker] Finalization error:', error)
    sendError(`Finalization failed: ${error}`)
  }
}

//=============================================================================
// Cleanup
//=============================================================================

function handleCleanup() {
  if (wasmExports && typeof wasmExports.cleanup === 'function') {
    wasmExports.cleanup()
  }

  wasmExports = null
  pluginMetadata = null

  // Cleanup streaming state
  streamActive = false
  streamChunks = []

  sendResponse({
    type: 'CLEANUP',
    payload: { success: true },
  })
}

//=============================================================================
// Tool ABI Support
//=============================================================================

function handleGetToolSchema() {
  try {
    if (!wasmExports) {
      throw new Error('Plugin not loaded')
    }

    if (typeof wasmExports.get_tool_schema !== 'function') {
      sendResponse({
        type: 'RESULT',
        payload: { toolSchema: null, isToolCapable: false },
      })
      return
    }

    const schemaJson = wasmExports.get_tool_schema()
    const schema = JSON.parse(schemaJson)

    sendResponse({
      type: 'RESULT',
      payload: { toolSchema: schema, isToolCapable: true },
    })
  } catch (error) {
    sendError(`Failed to get tool schema: ${error}`)
  }
}

function handleExecuteTool(payload: { input: string }) {
  try {
    if (!wasmExports) {
      throw new Error('Plugin not loaded')
    }

    if (typeof wasmExports.execute_tool !== 'function') {
      sendError('Plugin does not support tool execution (missing execute_tool export)')
      return
    }

    const outputJson = wasmExports.execute_tool(payload.input)
    const output = JSON.parse(outputJson)

    sendResponse({
      type: 'RESULT',
      payload: { toolOutput: output },
    })
  } catch (error) {
    sendError(`Tool execution failed: ${error}`)
  }
}

//=============================================================================
// Streaming Support
//=============================================================================

let streamActive = false
let streamChunks: StreamChunk[] = []

async function handleStreamStart(payload: { file: File; chunkSize: number }) {
  const { file, chunkSize } = payload

  try {
    streamActive = true
    streamChunks = []

    sendResponse({
      type: 'STREAM_READY',
      payload: {
        fileName: file.name,
        fileSize: file.size,
        chunkSize,
        totalChunks: Math.ceil(file.size / chunkSize),
      },
    })
  } catch (error) {
    handleStreamError({ error: `Stream start failed: ${error}` })
  }
}

async function handleStreamChunk(payload: {
  chunk: { index: number; data: string; offset: number; isLast: boolean }
  index: number
}) {
  const { chunk, index } = payload

  try {
    if (!streamActive) {
      throw new Error('No active streaming session')
    }

    streamChunks.push(chunk)

    if (chunk.isLast) {
      sendResponse({
        type: 'STREAM_CHUNK_ACK',
        payload: { index, isLast: true },
      })
    } else {
      sendResponse({
        type: 'STREAM_CHUNK_ACK',
        payload: { index, isLast: false },
      })
    }
  } catch (error) {
    handleStreamError({ error: `Stream chunk failed: ${error}` })
  }
}

function handleStreamEnd() {
  try {
    const chunks = [...streamChunks]
    streamActive = false
    streamChunks = []

    sendResponse({
      type: 'STREAM_COMPLETE',
      payload: {
        chunks,
        totalChunks: chunks.length,
      },
    })
  } catch (error) {
    handleStreamError({ error: `Stream end failed: ${error}` })
  }
}

function handleStreamError(payload: { error: string }) {
  streamActive = false
  streamChunks = []

  sendResponse({
    type: 'STREAM_ERROR',
    error: payload.error,
  })
}

//=============================================================================
// Helper Functions
//=============================================================================

function sendResponse(response: { type: string; payload?: unknown; error?: string }) {
  self.postMessage(response)
}

function sendError(error: string) {
  self.postMessage({
    type: 'ERROR',
    error,
  })
}

// Export types for TypeScript
export type {}
